Rules API: Enforce tenant label and id in rule expression
observatorium/api pull request #230
Opened 2022-02-04 21:20 UTC by jessicalins

To help with tenant rules validation (as mentioned in https://github.com/observatorium/api/issues/194), this PR adds a `tenant_id` label to metrics present in a `expr` field in a recording/alerting rule that is written via the Rules API (via `/api/v1/rules/raw` endpoint)

So for the following rule that is written via Rules API:
```yaml
groups:
- name: node_rules
  interval: 30s
  rules:
  - record: job:up:avg
    expr: avg without(instance)(up{job="node"})
  - alert: ManyInstancesDown
    expr: job:up:avg{job="node"} < 0.5
    for: 10m
    annotations:
      Summary: Many instances down
```
We expect that when the rule is read via `GET` request, the rule is changed with a `tenant_id` label is appended to `up` and `avg`:

`expr: avg without(instance)(up{job="node",tenant_id="tenantIDHere"})`
`expr: job:up:avg{job="node",tenant_id="tenantIDHere"} < 0.5`

I've also modified the current e2e tests to support this change.

Signed-off-by: Jéssica Lins <jessicaalins@gmail.com>

2022-02-08 11:58 UTC, ianbillett requested changes
Nice work @jessicalins :+1: 

One big question though - have you considered and discounted adding the tenant label into the rule spec itself rather than parsing and adding it into the query itself?

From the Prometheus rule [spec](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/):
```
# Labels to add or overwrite before storing the result.
labels:
  [ <labelname>: <labelvalue> ]
``` 

This would manifest here as an additional entry to the rule object, rather than parsing into the query itself.

2022-02-08 12:13 UTC, jessicalins commented
@ianbillett we actually already enforce the `tenant_id` label on returned rules (Lucas added [here](https://github.com/observatorium/api/pull/191/files)) and in the [spec](https://github.com/observatorium/api/blob/main/rules/spec.yaml#L112)

So a returned rule (before this PR) was already like: 
```yaml
groups:
- interval: 15s
  name: ruletwo
  rules:
  - expr: demo_test_metric
    labels:
      tenant_id: sdffsd34-c509-4592-a256-a18713657bfa
    record: job:demo_test_metric:ruletwometric
```

The problem is that when we query for a rule itself (e.g in this case, for `job:demo_test_metric:ruletwometric` - e.g. `http://127.0.0.1:8082/api/metrics/v1/oidc-two/api/v1/query?query=job:demo_test_metric:ruletwometric`) it would return metrics that match that rule, including rules from other tenants, instead of only the tenant rules.
So adding the tenant label to the `expr` helps with that. Discussed this with @onprem @saswatamcode - let me know if I'm missing something:)

2022-02-08 14:02 UTC, saswatamcode commented on test/e2e/rules_test.go
> +		assertResponse(t, bodyStr, "job:request_latency_seconds:mean5m{job=\"myjob\",tenant_id=\""+defaultTenantID+"\"}")
Maybe adding a more complex query like the ones we already use in rhobs/configuration would be a good idea here? 🙂

2022-02-08 18:38 UTC, jessicalins commented on test/e2e/configs.go
> +        expr: 0 * topk by (ebs_account) (1, max by (ebs_account,account_type,internal,email_domain) (label_replace(label_replace(label_replace(subscription_labels{email_domain="domain1.com"}*0+5, "cl
got it from [observatorium-metrics-template.yaml ](https://github.com/rhobs/configuration/blob/3978c8609271eb30fe16492af5f6b507ea86e139/resources/services/observatorium-metrics-template.yaml#L1340) in `rhobs/configuration`
I've just modified to be a more general expr, replacing `redhat` and `ibm` by `domain1` and `domain2`

2022-02-09 10:04 UTC, ianbillett submitted a review, later dismissed
Righto! I see - thanks for explaining. If you've discussed and agreed on this path forward with @onprem  & @saswatamcode then this solution works for me.

2022-02-09 10:42 UTC, matej-g approved these changes
Nice! 🍪

2022-02-09 10:42 UTC, matej-g commented on api/metrics/v1/rules.go
> +		http.Error(w, "error enforcing labels in rules", http.StatusInternalServerError)
Nit: I feel like this might be a bit cryptic in the response for the user, maybe something along the lines 'failed to process rules' would suffice.

2022-02-09 15:40 UTC, matej-g approved these changes

2022-02-09 15:40 UTC, merged